# Netlify Configuration for MarkDownUltraRemix
# Security-focused configuration for production deployment

[build]
  command = "bun run predeploy"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Security Headers Configuration
[[headers]]
  for = "/*"
  [headers.values]
    # Prevent clickjacking attacks
    X-Frame-Options = "DENY"
    
    # Prevent MIME type sniffing
    X-Content-Type-Options = "nosniff"
    
    # Enable XSS protection
    X-XSS-Protection = "1; mode=block"
    
    # Control referrer information
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Restrict dangerous browser features
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=()"
    
    # Force HTTPS (only in production)
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # Prevent DNS prefetching for privacy
    X-DNS-Prefetch-Control = "off"
    
    # Disable Adobe Flash and other plugins
    X-Permitted-Cross-Domain-Policies = "none"
    
    # Security headers for modern browsers
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"

# Cache optimization for static assets
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API routes security (if any)
[[headers]]
  for = "/api/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
    Cache-Control = "no-cache, no-store, must-revalidate"

# Note: Authentication uses modal/dialog, no separate auth routes needed

# Note: SPA routing handled by _redirects file in public folder
# This avoids conflicts between netlify.toml and _redirects

# Environment-specific settings
[context.production]
  [context.production.environment]
    NODE_ENV = "production"
    
[context.deploy-preview]
  [context.deploy-preview.environment]
    NODE_ENV = "production"
    
[context.branch-deploy]
  [context.branch-deploy.environment]
    NODE_ENV = "development"

# Functions configuration (if needed in future)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Build plugins for security scanning
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs.thresholds]
    performance = 0.8
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.8
